/* $Header:   K:\v4new\extcomp\callback\mac\xres.inv   1.0   15 Dec 1997 09:32:34   MMONSCHA  $ */

#define ES_LEFT           0L
#define ES_CENTER         0L
#define ES_RIGHT          0L
#define ES_MULTILINE      0L
#define ES_AUTOVSCROLL    0L
#define ES_AUTOHSCROLL    0L
#define ES_NOHIDESEL      0L

#define BS_PUSHBUTTON    	0L
#define BS_DEFPUSHBUTTON 	0L
#define BS_CHECKBOX      	0L
#define BS_AUTOCHECKBOX  	0L
#define BS_RADIOBUTTON   	0L
#define BS_3STATE        	0L
#define BS_AUTO3STATE    	0L
#define BS_GROUPBOX      	0L
#define BS_USERBUTTON    	0L
#define BS_ICNBUTTON     	0L
#define BS_TRIANGLEBUTT  	0L
#define BS_GRAYWHENDIS	 	0L

#define LBS_NOTIFY        0x0000L
#define LBS_SORT          0x0000L
#define LBS_NOREDRAW      0x0000L
#define LBS_MULTIPLESEL   0x0000L
#define LBS_NOINTEGRALHEIGHT   0x000L
#define CBS_DROPDOWNLIST	0x0000L
#define CBS_SPLITTERBAR		0x0000L
#define SPB_VERT					0x0000L
#define SPB_HORZ					0x0000L

#define SS_LEFT       0L
#define SS_CENTER     0L
#define SS_RIGHT      0L
#define SS_ICON       0L
#define SS_BLACKRECT  0L
#define SS_GRAYRECT   0L
#define SS_WHITERECT  0L
#define SS_BLACKFRAME 0L
#define SS_GRAYFRAME  0L
#define SS_WHITEFRAME 0L
#define SS_USERITEM   0L

#define WS_TILED        0x00000000L
#define WS_POPUP        0x00000000L
#define WS_CHILD        0x00000000L   
#define WS_ICONIC       0x00000000L

#define WS_VISIBLE      0x10000000L
#define WS_DISABLED     0x08000000L
#define WS_CLIPSIBLINGS 0x04000000L
#define WS_CLIPCHILDREN 0x02000000L
#define WS_MINIMIZEBOX  0x00020000L   
#define WS_MAXIMIZEBOX  0x00010000L   

#define WS_BORDER       0x00800000L
#define WS_CAPTION      0x00c00000L
#define WS_DLGFRAME     0x00400000L
#define WS_VSCROLL      0x00200000L
#define WS_HSCROLL      0x00100000L
#define WS_SYSMENU      0x00080000L
#define WS_SIZEBOX      0x00040000L
#define WS_GROUP        0x00000000L
#define WS_TABSTOP      0x00000000L
#define WS_PALETTE 			0x00000001L
#define WS_TOOLBAR     	0x00000002L
#define WS_TOOLGROUP   	0x00000004L

#define LBS_STANDARD      (LBS_NOTIFY | LBS_SORT | WS_VSCROLL | WS_BORDER)

#define SBS_HORZ                    0x0000L
#define SBS_VERT                    0x0001L
#define SBS_TOPALIGN                0x0002L
#define SBS_LEFTALIGN               0x0002L
#define SBS_BOTTOMALIGN             0x0004L
#define SBS_RIGHTALIGN              0x0004L
#define SBS_SIZEBOXTOPLEFTALIGN     0x0002L
#define SBS_SIZEBOXBOTTOMRIGHTALIGN 0x0004L
#define SBS_SIZEBOX                 0x0008L


