# $Header: https://172.16.3.39/repos/trunk/Studio/EXTCOMP/GENERIC/UNIX/makefile 10588 2014-10-08 10:13:22Z pashworth $
# makefile for Linux (gcc C++ compiler)
#
###### Project

PROJ_NAME = osxhelp
WEB_NAME = osxhelp

##############################################################################
# Add your objects, dependencies and resource file here

objects = osxhelp.o xosxhelp.o

DEPENDENCIES = osxhelp.he xosxhelp.he

RCFILE = osxhelp.rc

include ../complib/extcomp.mak
